sonar.projectKey=mylttpjt
sonar.projectName=MY GO-LANG PROJECT
sonar.sources=.
sonar.exclusions=**/*_test.go,**/vendor/**
sonar.tests=.
sonar.test.inclusions=**/*_test.go
# Path to your unit test coverage report (this will be picked up by SonarQube)
sonar.go.coverage.reportPaths=coverage.out