name: Go CI Pipeline

on:
  push:
    branches:
      - '**'
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  run-shared-pipeline:
    uses: Prakashdurai/cicd-template/.github/workflows/go-ci-template.yml@main
    with:
      go-version: '1.25'
      gobuildcommand: 'go build -ldflags="-s -w" -o bin/main cmd/main.go'
      # CONFIGURE TO RUN STATIC ANALYSIS ONLY
      run-build: true
      run-sa: true
      run-ut: true
    secrets: inherit
